/**
 * 默认样式 — 从旧 stableStyles 迁移，camelCase 键名
 *
 * 值保持 DOM 风格：带单位（"16pt"）、颜色（"#ff0000"）、类名（"roundedRect"）
 * "none" 表示无，null/undefined 表示继承父级
 */

import type { ResolvedStyle, NodeType, StyleValue } from './style-types'

export const DEFAULT_STYLES: Record<NodeType, ResolvedStyle> = {
  centralTopic: {
    fontWeight: 'normal',
    fontColor: '#FFFFFF',
    fontFamily: '$system$',
    fontStyle: 'normal',
    fontSize: '28pt',
    textDecoration: 'none',
    textTransform: 'manual',
    shapeClass: 'roundedRect',
    fillColor: '#2A7AC2',
    fillPattern: 'solid',
    lineClass: 'curve',
    lineColor: '#333333',
    lineWidth: '2pt',
    borderColor: 'none',
    borderWidth: '0pt',
    borderPattern: 'solid',
    lineCorner: '16pt',
    linePattern: 'solid',
    arrowEndClass: 'none',
    marginLeft: '29pt',
    marginRight: '29pt',
    marginTop: '15pt',
    marginBottom: '15pt',
    spacingMajor: '50pt',
    spacingMinor: '35pt',
  },
  mainTopic: {
    fontWeight: 'normal',
    fontColor: '#333333',
    fontFamily: '$system$',
    fontStyle: 'normal',
    fontSize: '16pt',
    textDecoration: 'none',
    textTransform: 'manual',
    shapeClass: 'roundedRect',
    fillColor: '#E8E8E8',
    fillPattern: 'solid',
    lineClass: 'roundedElbow',
    lineColor: '#333333',
    lineWidth: '1pt',
    borderColor: '#333333',
    borderWidth: '1pt',
    borderPattern: 'solid',
    shapeCorner: '5pt',
    lineCorner: '8pt',
    linePattern: 'solid',
    arrowEndClass: 'none',
    marginLeft: '18pt',
    marginRight: '18pt',
    marginTop: '10pt',
    marginBottom: '10pt',
    spacingMajor: '26pt',
    spacingMinor: '6pt',
  },
  subTopic: {
    fontWeight: 'normal',
    fontColor: '#0A0E16',
    fontFamily: '$system$',
    fontStyle: 'normal',
    fontSize: '12pt',
    textDecoration: 'none',
    textTransform: 'manual',
    shapeClass: 'underline',
    fillColor: 'none',
    fillPattern: 'solid',
    lineClass: 'roundedElbow',
    lineColor: '#232323',
    lineWidth: '1pt',
    borderColor: '#232323',
    borderWidth: '1pt',
    borderPattern: 'solid',
    shapeCorner: '3pt',
    lineCorner: '8pt',
    linePattern: 'solid',
    arrowEndClass: 'none',
    marginLeft: '6pt',
    marginRight: '6pt',
    marginTop: '6pt',
    marginBottom: '6pt',
    spacingMajor: '26pt',
    spacingMinor: '8pt',
  },
  floatingTopic: {
    fontWeight: 'normal',
    fontColor: '#FFFFFF',
    fontFamily: '$system$',
    fontStyle: 'normal',
    fontSize: '14pt',
    textDecoration: 'none',
    textTransform: 'manual',
    shapeClass: 'roundedRect',
    shapeCorner: '8pt',
    fillColor: '#333333',
    fillPattern: 'solid',
    lineClass: 'roundedElbow',
    lineColor: '#333333',
    lineWidth: '1pt',
    lineCorner: '8pt',
    linePattern: 'solid',
    borderColor: '#333333',
    borderWidth: '0pt',
    borderPattern: 'solid',
    arrowEndClass: 'none',
    marginLeft: '11pt',
    marginRight: '11pt',
    marginTop: '11pt',
    marginBottom: '11pt',
    spacingMajor: '26pt',
    spacingMinor: '8pt',
  },
  calloutTopic: {
    fontWeight: 'normal',
    fontColor: '#FFFFFF',
    fontFamily: '$system$',
    fontStyle: 'italic',
    fontSize: '12pt',
    textDecoration: 'none',
    textTransform: 'manual',
    calloutShapeClass: 'roundedRect',
    fillColor: '#333333',
    fillPattern: 'solid',
    lineClass: 'curve',
    lineColor: '#333333',
    lineWidth: '1pt',
    borderColor: 'none',
    borderWidth: '1pt',
    borderPattern: 'solid',
    shapeCorner: '5pt',
    lineCorner: '8pt',
    linePattern: 'solid',
    arrowEndClass: 'none',
    marginLeft: '6pt',
    marginRight: '6pt',
    marginTop: '6pt',
    marginBottom: '6pt',
    spacingMajor: '26pt',
    spacingMinor: '8pt',
  },
  summaryTopic: {
    fontWeight: 'normal',
    fontColor: '#FFFFFF',
    fontFamily: '$system$',
    fontStyle: 'italic',
    fontSize: '14pt',
    textDecoration: 'none',
    shapeClass: 'roundedRect',
    shapeCorner: '5pt',
    fillColor: '#333333',
    fillPattern: 'solid',
    marginLeft: '12pt',
    marginRight: '12pt',
  },
  boundary: {
    shapeClass: 'roundedRect',
    fillColor: '#D5E9FC',
    lineColor: '#5291E5',
    linePattern: 'dash',
    lineWidth: '1pt',
    opacity: 0.2,
    shapeCorner: '5pt',
    fontFamily: '$system$',
    fontSize: '14pt',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textTransform: 'manual',
    textDecoration: 'none',
    fillPattern: 'solid',
  },
  summary: {
    shapeClass: 'square',
    lineColor: '#5291E5',
    lineWidth: '1pt',
    lineCorner: '8pt',
    linePattern: 'solid',
  },
  relationship: {
    lineClass: 'curve',
    lineColor: '#5291E5',
    linePattern: 'dash',
    lineWidth: '1pt',
    arrowEndClass: 'triangle',
    lineCorner: '8pt',
    fontFamily: '$system$',
    fontSize: '14pt',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textTransform: 'manual',
    textDecoration: 'none',
  },
  map: {
    lineTapered: 'none',
    multiLineColors: 'none',
  },
}

/** 获取默认样式值 */
export function getDefaultStyle(nodeType: NodeType, key: string): StyleValue {
  return DEFAULT_STYLES[nodeType]?.[key]
}
